name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Указываем Windows как среду выполнения

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable  # Или любой другой таргет, например, nightly

    - name: Build project
      run: cargo build --release

    - name: Run tests
      run: cargo test
